version: '3.9'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=airat
      - POSTGRES_PASSWORD=1e2r3Tb7$
      - POSTGRES_DB=todo_db
    ports:
      - '5432:5432'
    volumes:
      - ./db_data/:/var/lib/postgres/data
