version: '3.9'
services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - src/.env
    ports:
      - '5432:5432'
    volumes:
      - pg_data_todolist:/var/lib/postgres/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  pg_data_todolist:

networks:
  backend_nw:
    driver: bridge