version: '3.10'

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - ./src/.env
    volumes:
      - pg_data_todolist:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 3
  api:
    image: ${DOCKERHUB_USERNAME}/diploma6:latest
    restart: always
    env_file:
      - ./src/.env
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: airat/skypro-front:lesson-34
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


volumes:
  pg_data_todolist:

networks:
  backend_nw:
    driver: bridge
